### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by MonoAdrian23** [roci33/MorphX#2]
Permissions doesnt work.
morphx.command.morph
morphx.command
Pocketmine 3.11.5
MorphX Latest

**Comment by roci33** [comment]
Do you use PurePerms to set permissions?

**Comment by MonoAdrian23** [comment]
Yes

**Comment by roci33** [comment]
Strange, would you write me the command you execute?

**Comment by MonoAdrian23** [comment]
It works for OP
When a player types /morph list ore /morph wither or another mob. You dont have Permissions.
But i have the Permissions given.
Sorry for my Englisch iam German

**Comment by MonoAdrian23** [comment]
/fperms show my only these both Permissions

**Comment by jaylac2000** [comment]
look in plugin.yml for permissions

**Comment by roci33** [comment]
Okay, but you have to set permission for a player or tag (you do this with the PurePerms plugin), did you do it?  and if so what command did you do to set the permission to the player / tag?

**Comment by jaylac2000** [comment]
i didnt have perm issues my self, although when i try and disguise myself it keeps my player as my skin. it its supposed to do that than maybe i can make a suggestion that it changes to whatever you disguised yourself as

**Comment by MonoAdrian23** [comment]
I just wrote the permissions into the groups

**Comment by roci33** [comment]
I understand the error, it is a small bug in the plugin.yml, it will be resolved by today, thanks for the report!

**Comment by MonoAdrian23** [comment]
Thank you very much
This Plugin is very good.
Thanks for youre hard work.

**Comment by roci33** [comment]
Ok I fixed the problem, download the new version and reset the permission (permission: morphx.command.morph)
