### ISSUE TITLE
blocks vision and movement is awkward

### ISSUE THREAD

**Issue by ghost** [roci33/MorphX#3]
if you morph into a zombie for example and be in first person perspective you can't see anything at all, also if you morph and move a little bit the entity keeps moving and shaking while you are just standing still.

**Comment by roci33** [comment]
Hello, thank you very much for your report.  In fact, for now the plugin is to be used by putting itself in 2 people, soon I will try to implement a system that allows the player not to see that entity, so as not to cause these problems.  For now the plugin is better to use it in 2/3 person

**Comment by roci33** [comment]
Regarding the problem that the mob when you stop a few times moving your legs will be resolved by today / tomorrow

**Comment by ghost** [comment]
thank you.

**Comment by roci33** [comment]
Okay, tomorrow i fix

**Comment by ghost** [comment]
u shouldn't close an issue before its 100% fixed tho
