### ISSUE TITLE
Fall Damage

### ISSUE THREAD

**Issue by ghost** [roci33/MorphX#6]
When you jump the entity sometimes takes damage, eventually killing it. When you fly down, or exit fly mode in the air, when you hit the ground the entity dies. This leaves you invisible with no entity.

**Comment by roci33** [comment]
Hello, thanks for reporting the bug, it will be fixed soon. 

 P.S the bugs you report will be resolved by today / tomorrow goodbye

**Comment by roci33** [comment]
1.0.0 of the plugin has just been released, this problem has been solved!
