### ISSUE TITLE
entity doesn't despawn after quit

### ISSUE THREAD

**Issue by ghost** [roci33/MorphX#7]
if you spawn an entity and quit it doesn't despawn and when u join again you have to remove it manualy then you may morph into a mob again. so put a check on quit if the player has an entity spawned and remove it , also it would be better if you could make it remove the entity automatically when morphing into a mob while being already a mob (ex: morphing to sheep then morphing to wolf without doing '/morph remove' in between)

**Comment by roci33** [comment]
Hello, to solve your problem you don't have to remove the entity manually, but do the command (/ m remove, even if you have quit without running the command ) this command is equipped with a system that solves the bugs generated by an entity by itself.  I also thank you for your advice!

**Comment by ghost** [comment]
doing the command is what i mean by removing it manualy, it should automatically remove itself when switching entities or when the player quits and it doesn't do that now

**Comment by roci33** [comment]
Okay, I will try to solve the problem in the next version of the plugin!  should be out in a few days, thanks for reporting the bug.
Goodbye!

**Comment by ghost** [comment]
also i have 2 requests
1- when you fly the entity is despawned but when you stop flying entity doesn respawn, how about you put a check when the player flys if he has spawned an entity put his name and entity info in an array and when the player is not flying check if he is set in the array and then spawn the entity back for him

2- please add back the invisibility effect because seeing both player skin and the entity is not pleasing and for sure not a good thing specially that players will be on third person perspective and they will want to see how they look to other people or if they want to screen shot it

**Comment by roci33** [comment]
Ok, thanks for the advice, for the first question, the system you recommend would bring several bugs, for this reason I don't think to adopt it.  When you fly the entity is removed to avoid additional bug / lag.  Regarding the second question I see to reaffirm the effect of envy even if as I have specified only you can see yourself when you are in morph

**Comment by ghost** [comment]
its true that only me can see me but what if i don't want to see me tho?

**Comment by roci33** [comment]
1.0.0 of the plugin has just been released, this problem has been solved!
